version: '3'
services:
  t3docmake:
    image: t3docs/render-documentation:latest
    command: makehtml
    volumes:
      - ./:/PROJECT:ro
      - ./Documentation-GENERATED-temp:/RESULT
# build documentation with "docker-compose run --rm t3docmake"
