services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EHAERER\PasteReference\:
    resource: '../Classes/*'

  EHAERER\PasteReference\Hooks\PageLayoutController:
    public: true

  EHAERER\PasteReference\ContextMenu\PasteReferenceItemProvider:
    tags:
      - name: backend.contextmenu.itemprovider

  EHAERER\PasteReference\EventListener\ExtTablesInclusionPostProcessing:
    tags:
      - name: event.listener
        identifier: 'paste-reference/after-tca-compilation-event'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  EHAERER\PasteReference\EventListener\ModifyPageLayoutContentListener:
    tags:
      - name: event.listener
        identifier: 'paste-reference/backend/modify-page-module-content'
